on: push
jobs:
  build-cv:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Setup mamba and environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
      - name: Build PDF w/ Garamond fonts
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          args: -latex='latex -shell-esc -interaction=nonstopmode %O \\\def\\\iscockrell{1} \\\input %S' -jobname="cv_cockrell"
      - name: Clean build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          args: -C
      - name: Rebuild
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          args: 
      - name: Build html version
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          args: -pdf
          post_compile: |
            vi cv.html +"set fileencoding=utf-8" +qall +wq 
            pandoc cv.html -o cv.docx
