on: push
jobs:
  build-cv:
    runs-on: "ubuntu-latest"
    container: 
      image: johntfoster/texlive:latest
      volumes: 
        - ${{ github.workspace }}:/var/texlive
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Cockrell School version
        run: latexmk -pdfxe cv.tex
      - name: Build HTML version
        run: latexmk -pdfxe cv.tex
      - name: Convert html to docx
        run: |
          vi cv.html +"set fileencoding=utf-8" +qall +wq 
          pandoc cv.html -o cv.docx
