on: push
jobs:
  build-cv:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Setup mamba and environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
      - name: Rebuild
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          args: -pdfxe
      - name: Build html version
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          args: -pdf -dvi- -ps-
      - name: Convert html to docx
        shell: bash -l {0}
        run: |
          sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends vim
          vi cv.html +"set fileencoding=utf-8" +qall +wq 
          pandoc cv.html -o cv.docx
