on: 
  push:
    branches: [master]
jobs:
  build-cv:
    runs-on: "ubuntu-latest"
    container: 
      image: johntfoster/texlive:latest
      options: -w /usr/src/app
      volumes: 
        - ${{ github.workspace }}:/usr/src/app
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build personal version
        run: latexmk -jobname="cv_personal" cv.tex
      - name: Build Cockrell School version
        run: latexmk -pdfxe -jobname="cv_cockrell" cv.tex
      - name: Build html version
        run: latexmk -pdf cv.tex
      - name: Convert html to docx
        run: |
          vi cv.html +"set fileencoding=utf-8" +qall +wq 
          pandoc cv.html -o cv.docx
      - name: Commit changes to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          branch: gh-actions-autocommit
          file_pattern: cv_personal.pdf cv_cockrell.pdf cv.html cv.docx
          commit_user_name: John T. Foster
          commit_user_email: johntfosterjr@gmail.com
          push_options: --force
          skip_fetch: true
          skip_checkout: true
      - name: Trigger website rebuild
        shell: bash -l {0}
        run: |
          curl --request POST \
          --url 'https://api.github.com/repos/johnfoster-pge-utexas/johnfoster-pge-utexas.github.io/dispatches' \
          --header 'authorization: Bearer ${{ secrets.GH_SECRET_TOKEN }}' \
          --data '{"event_type": "trigger"}'
