on: push
jobs:
  build-cv:
    runs-on: "ubuntu-latest"
    container: 
      image: johntfoster/texlive:latest
      options: -w /usr/src/app
      volumes: 
        - ${{ github.workspace }}:/usr/src/app
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build personal version
        run: latexmk cv.tex
      - name: Build Cockrell School version
        run: latexmk -pdfxe -jobname="cv_cockrell" cv.tex
      - name: Build html version
        run: latexmk -pdf cv.tex
      - name: Convert html to docx
        run: |
          vi cv.html +"set fileencoding=utf-8" +qall +wq 
          pandoc cv.html -o cv.docx
      - name: Commit changes to branch
        uses: EndBug/add-and-commit@v7
        with: 
          add: 'cv.pdf cv_cockrell.pdf cv.html cv.docx'
          author_name: John T. Foster
          author_email: johntfosterjr@gmail.com
          branch: gh-actions-autocommit
