on: 
  push:
    branches: [master]
jobs:
  build-cv:
    runs-on: "ubuntu-latest"
    container: 
      image: johntfoster/texlive:latest
      options: -w /usr/src/app
      volumes: 
        - ${{ github.workspace }}:/usr/src/app
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Cockrell School version
        run: latexmk -pdfxe -jobname="cv_cockrell" cv.tex
      - name: Clean
        run: latexmk -c -jobname="cv_cockrell"
      - name: Build personal version
        run: latexmk cv.tex
      - name: Build html version
        run: latexmk -pdf cv.tex
      - name: Convert html to docx
        run: |
          vi cv.html +"set fileencoding=utf-8" +qall +wq 
          pandoc cv.html -o cv.docx
      - name: Commit changes to branch
        uses: EndBug/add-and-commit@v7
        with: 
          add: cv.pdf cv_cockrell.pdf cv.html cv.docx
          author_name: John T. Foster
          author_email: johntfosterjr@gmail.com
          branch: gh-actions-autocommit
          pull_strategy: 'NO-PULL'
          push: 'origin gh-actions-autocommit -f'
      - name: Trigger website rebuild
        shell: bash -l {0}
        run: |
          curl --request POST \
          --url 'https://api.github.com/repos/johnfoster-pge-utexas/johnfoster-pge-utexas.github.io/dispatches' \
          --header 'authorization: Bearer ${{ secrets.GH_SECRET_TOKEN }}' \
          --data '{"event_type": "trigger"}'
